version: 2

project_name: prpilot

builds:
  - main: ./cmd/prpilot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"
    binary: prpilot

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

release:
  draft: false
  prerelease: false
  github:
    owner: bjess9
    name: prpilot
