version: '3.8'

services:
  pr-pilot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pr-pilot-dev
    environment:
      # GitHub authentication - set these in your .env file
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      # Mount local config directory for persistence
      - ./config:/root/.config
      # Mount host's .gitconfig for git operations
      - ~/.gitconfig:/root/.gitconfig:ro
      # Optional: Mount GitHub CLI config if using gh auth
      - ~/.config/gh:/root/.config/gh:ro
    networks:
      - pr-pilot-network
    restart: unless-stopped
    # Override the default entrypoint for development
    # command: ["tail", "-f", "/dev/null"]  # Uncomment to keep container running for debugging
    
  # Optional: Development database if we add data persistence later
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: pr-pilot-db
  #   environment:
  #     POSTGRES_DB: prpilot
  #     POSTGRES_USER: prpilot
  #     POSTGRES_PASSWORD: prpilot_dev
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - pr-pilot-network

  # Optional: Redis for caching (future feature)
  # redis:
  #   image: redis:7-alpine
  #   container_name: pr-pilot-redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - pr-pilot-network
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - redis_data:/data

networks:
  pr-pilot-network:
    driver: bridge

# volumes:
#   postgres_data:
#   redis_data:
